name: halloween_hunt
description: A new Flutter project.
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flame: ^1.2.1
  flame_audio: ^1.3.1
  flame_forge2d: ^0.12.2
  flame_mini_sprite: ^0.0.1
  flutter:
    sdk: flutter
  mini_sprite: ^0.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true

  assets:
    - assets/audio/game_over.wav
    - assets/audio/jump.wav
    - assets/audio/victory.wav
    - assets/audio/bgm.mp3

  fonts:
    - family: Pixeloid
      fonts:
        - asset: assets/fonts/PixeloidSans-nR3g1.ttf
          
  
  
  
  
  
  
  
  
